"""
Django settings for bomnado project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
import sys
import _locale
import logging
from bomnado.settings import get_int_environment_var

log = logging.getLogger()

# Never use this in production!
DEFAULT_SECRET_KEY = "django-insecure-12345"
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', DEFAULT_SECRET_KEY)
SHOW_KEY_WARNING = SECRET_KEY == DEFAULT_SECRET_KEY  # Show the user a big red warning when they're using the default key
if SHOW_KEY_WARNING:
    log.warning('DJANGO_SECRET_KEY is set to the default Value! Please generate a new secret key when publishing this Bomnado instance')


try:
    from definitions import ROOT_DIR
except ImportError:
    # Use the working directory and warn the user.
    ROOT_DIR = os.getcwd()
    print("WARNING: ROOT_DIR not defined in definitions.py, using current working directory")

_locale._getdefaultlocale = (lambda *args: ['en_GB', 'utf8'])

# Application definition

INSTALLED_APPS = [
    'bom',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_cleanup.apps.CleanupConfig',
    'rest_framework',
    'django_celery_results',
    'dbbackup',
    'general',
]

TESTING = sys.argv[1:2] == ['test']
if TESTING:
    # Use Django's default test runner (compatible with Python 3.12)
    # Remove nose-specific configuration as nose is incompatible with Python 3.12
    pass

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Add FirstTimeSetupMiddleware only if not running tests
if 'test' not in sys.argv:
    MIDDLEWARE.append('bom.middleware.FirstTimeSetupMiddleware')

ROOT_URLCONF = 'bomnado.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'bom.context_processors.security_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'bomnado.wsgi.application'

AUTHENTICATION_BACKENDS = ['bom.auth.backends.EmailBackend']

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-GB'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(ROOT_DIR, 'static')

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ]
}

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# See: https://docs.djangoproject.com/en/5.2/ref/settings/#csrf-cookie-httponly
CSRF_COOKIE_HTTPONLY = False

# Media Path
MEDIA_URL = '/media/'
MEDIA_ROOT = 'media'

LOGOUT_REDIRECT_URL = "/"
LOGIN_REDIRECT_URL = "/"

DJANGO_CRON_DELETE_LOGS_OLDER_THAN = 7  # Keep Cron Logs for 7 Days


DBBACKUP_CLEANUP_KEEP = get_int_environment_var('DBBACKUP_CLEANUP_KEEP', 7)
DBBACKUP_CLEANUP_KEEP_MEDIA = get_int_environment_var('DBBACKUP_CLEANUP_KEEP_MEDIA', 7)

# Storage backends configuration - explicitly setting all storages
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
    "dbbackup": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
        "OPTIONS": {
            "location": os.path.join(ROOT_DIR, 'backups'),
        },
    },
}

# Also set the legacy STATICFILES_STORAGE for compatibility with older Django versions
# This ensures static files work reliably across different environments
STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"

# Project version.
VERSION = '0.21.0'

# Program settings
BOM_MAX_RECENT_ASSEMBLIES = 5
"""The number of recently viewed assemblies to keep a record for users"""