# Generated by Django 3.0.8 on 2020-07-28 09:20

import bom.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('bom', '0001_initial'), ('bom', '0002_auto_20200430_1601'), ('bom', '0003_partsource_shipping'), ('bom', '0004_auto_20200504_1054'), ('bom', '0005_auto_20200504_1105'), ('bom', '0006_subassembly_instructions'), ('bom', '0007_part_spec'), ('bom', '0008_auto_20200509_2242'), ('bom', '0009_auto_20200509_2259'), ('bom', '0010_auto_20200509_2323'), ('bom', '0011_auto_20200510_1112'), ('bom', '0012_auto_20200510_1425'), ('bom', '0013_part_picture'), ('bom', '0014_auto_20200511_1427'), ('bom', '0015_auto_20200515_2106'), ('bom', '0016_auto_20200515_2110'), ('bom', '0017_auto_20200515_2125'), ('bom', '0018_auto_20200515_2304'), ('bom', '0019_auto_20200515_2317'), ('bom', '0020_auto_20200515_2319'), ('bom', '0021_auto_20200515_2328'), ('bom', '0022_auto_20200515_2334'), ('bom', '0023_auto_20200515_2352'), ('bom', '0024_remove_subassembly_explosiondate'), ('bom', '0025_auto_20200516_1611'), ('bom', '0026_auto_20200517_1611'), ('bom', '0027_auto_20200517_1741'), ('bom', '0028_auto_20200519_0026'), ('bom', '0029_auto_20200519_2034'), ('bom', '0030_part_end_of_life')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^[0-9A-Z-]*$', 'Only uppercase letters, numbers, and dashes are allowed.')])),
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('kgs', models.FloatField(default=0.0)),
                ('spec', models.TextField(blank=True)),
                ('colour', models.CharField(blank=True, max_length=100)),
                ('dimensions', models.CharField(blank=True, max_length=100)),
                ('nature', models.CharField(choices=[('S', 'Standard'), ('B', 'Bespoke')], default='S', max_length=1)),
                ('picture', models.ImageField(blank=True, storage=bom.models.OverwriteStorage(), upload_to=bom.models.upload_part_picture_path)),
                ('sale_code', models.CharField(blank=True, max_length=100)),
                ('end_of_life', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubAssembly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^[0-9A-Z-]*$', 'Only uppercase letters, numbers, and dashes are allowed.')])),
                ('name', models.CharField(max_length=200)),
                ('revision', models.CharField(max_length=20, validators=[bom.models.validate_semver])),
                ('is_toplevel', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('instructions', models.TextField(blank=True)),
                ('sale_code', models.CharField(blank=True, max_length=100)),
                ('picture', models.ImageField(blank=True, storage=bom.models.OverwriteStorage(), upload_to=bom.models.upload_assembly_picture_path)),
            ],
        ),
        migrations.CreateModel(
            name='PartSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True)),
                ('lead_time', models.IntegerField(default=1)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('rrp', models.FloatField(default=0.0)),
                ('minimum_order', models.IntegerField(default=1)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='bom.Part', verbose_name='Part')),
                ('partcode', models.CharField(default='', max_length=100)),
                ('shipping', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='SubAssemblyLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('child_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bom.Part')),
                ('child_subassembly', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_subassembly', to='bom.SubAssembly')),
                ('subassembly', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='bom.SubAssembly')),
            ],
        ),
    ]
