# Generated by Django 3.0.8 on 2020-07-29 11:36

import bom.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0001_squashed_0030_part_end_of_life'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='reference',
            field=models.CharField(default=bom.models.get_default_reference, max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^[0-9A-Z-]*$', 'Only uppercase letters, numbers, and dashes are allowed.')]),
        ),
        migrations.AlterField(
            model_name='subassembly',
            name='reference',
            field=models.CharField(default=bom.models.get_default_reference, max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^[0-9A-Z-]*$', 'Only uppercase letters, numbers, and dashes are allowed.')]),
        ),
    ]
