# Generated by Django 3.1 on 2020-10-17 14:11

import bom.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0003_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='attachment_file',
            field=models.FileField(upload_to=bom.models.upload_attachment_path),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
