# Generated by Django 3.1 on 2020-10-17 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0004_auto_20201017_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='attachment',
            old_name='modified',
            new_name='updated',
        ),
    ]
