# Generated by Django 3.1 on 2020-10-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0005_auto_20201017_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='subassembly',
            name='qc_steps',
            field=models.TextField(blank=True),
        ),
    ]
