# Generated by Django 3.1 on 2020-10-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0006_subassembly_qc_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='partsource',
            name='order_notes',
            field=models.TextField(blank=True),
        ),
    ]
