# Generated by Django 3.1 on 2020-10-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0007_partsource_order_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='deprecated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subassembly',
            name='deprecated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
