# Generated by Django 3.1 on 2020-10-19 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0008_auto_20201019_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='subassembly',
            name='spec',
            field=models.TextField(blank=True),
        ),
    ]
