# Generated by Django 3.1 on 2020-10-23 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0009_subassembly_spec'),
    ]

    operations = [
        migrations.AddField(
            model_name='subassembly',
            name='production_phase',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
