# Generated by Django 3.1 on 2021-01-15 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0011_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='bom.team', verbose_name='Team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subassembly',
            name='shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subassembly',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assemblies', to='bom.team', verbose_name='Team'),
            preserve_default=False,
        ),
    ]
