# Generated by Django 3.1 on 2021-01-18 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0012_team_ownership'),
    ]

    operations = [
        migrations.AddField(
            model_name='subassembly',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='bom.subassembly', verbose_name='Project', default=1),
        ),
    ]
