# Generated by Django 3.1 on 2021-01-20 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0013_project_assembly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subassembly',
            name='project',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='children', to='bom.subassembly', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.TextField(max_length=150, unique=True),
        ),
    ]
