# Generated by Django 3.1 on 2021-02-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0014_delete_orphan_noncascade'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='hs_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='subassembly',
            name='hs_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
