# Generated by Django 3.1 on 2021-04-06 08:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0015_auto_20210217_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('rrp', models.FloatField(default=0.0)),
                ('shipping', models.FloatField(default=0.0)),
                ('lead_time', models.IntegerField(default=1)),
                ('order_notes', models.TextField(blank=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DealLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bom.deal')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bom.part')),
            ],
        ),
        migrations.AddField(
            model_name='deal',
            name='parts',
            field=models.ManyToManyField(through='bom.DealLineItem', to='bom.Part'),
        ),
        migrations.AddField(
            model_name='deal',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='bom.team', verbose_name='Team'),
        ),
    ]
