# Generated by Django 3.1 on 2022-02-25 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0016_deals'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='project',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='deals', to='bom.subassembly', verbose_name='Project'),
        ),
    ]
