# Generated by Django 3.1 on 2022-06-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0017_dealproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='qc_steps',
            field=models.TextField(blank=True),
        ),
    ]
