# Generated by Django 3.1 on 2022-06-30 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0018_part_qc_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subassembly',
            name='review_notes',
            field=models.TextField(blank=True),
        ),
    ]
