# Generated by Django 5.2.6 on 2026-08-11 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0021_team_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='PCBPart',
            fields=[
                ('part_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bom.part')),
                ('LCSCPartNo', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'PCB Part',
                'verbose_name_plural': 'PCB Parts',
            },
            bases=('bom.part',),
        ),
    ]
