# Generated by Django 5.2.6 on 2026-08-11 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0022_pcbpart'),
    ]

    operations = [
        migrations.CreateModel(
            name='PCBSubAssembly',
            fields=[
                ('subassembly_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bom.subassembly')),
            ],
            options={
                'verbose_name': 'PCB SubAssembly',
                'verbose_name_plural': 'PCB SubAssemblies',
            },
            bases=('bom.subassembly',),
        ),
    ]
