# Generated by Django 5.2.6 on 2026-08-22 10:30

import bom.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0027_pcbpart_category_datasheetlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='NamedPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suffix', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[0-9A-Z-]*$', 'Only uppercase letters, numbers, and dashes are allowed.')])),
                ('note', models.CharField(blank=True, max_length=200)),
                ('picture', models.ImageField(blank=True, storage=bom.models.OverwriteStorage(), upload_to=bom.models.upload_piece_picture_path)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='named_pieces', to='bom.part', verbose_name='Part')),
            ],
            options={
                'ordering': ['suffix'],
                'unique_together': {('part', 'suffix')},
            },
        ),
    ]
