# Generated by Django 5.2.6 on 2026-08-26 13:14

import bom.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0027_pcbpart_category_datasheetlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='subassembly',
            name='original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forks', to='bom.subassembly'),
        ),
        migrations.AlterField(
            model_name='subassembly',
            name='reference',
            field=models.CharField(default=bom.models.get_default_reference, max_length=100, validators=[django.core.validators.RegexValidator('^[0-9A-Z-]*$', 'Only uppercase letters, numbers, and dashes are allowed.')]),
        ),
    ]
