# Generated by Django 5.2.6 on 2026-08-22 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0030_feedback_from_review_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpart',
            name='review_notes',
        ),
        migrations.RemoveField(
            model_name='historicalpcbpart',
            name='review_notes',
        ),
        migrations.RemoveField(
            model_name='historicalpcbsubassembly',
            name='review_notes',
        ),
        migrations.RemoveField(
            model_name='historicalsubassembly',
            name='review_notes',
        ),
        migrations.RemoveField(
            model_name='part',
            name='review_notes',
        ),
        migrations.RemoveField(
            model_name='subassembly',
            name='review_notes',
        ),
    ]
