# Generated by Django 5.2.6 on 2026-08-22 17:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0031_remove_review_notes'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('scrape_url', 'Create a part from a link'), ('scrape_file', 'Create a part from a datasheet'), ('alternatives', 'Find alternative suppliers'), ('ingest', 'Turn notes and files into parts')], max_length=20)),
                ('status', models.CharField(choices=[('queued', 'queued'), ('running', 'running'), ('done', 'done'), ('executed', 'executed'), ('failed', 'failed')], default='queued', max_length=10)),
                ('model', models.CharField(blank=True, max_length=50)),
                ('input', models.JSONField(blank=True, default=dict)),
                ('messages', models.JSONField(blank=True, default=list)),
                ('result', models.JSONField(blank=True, null=True)),
                ('outcome', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('web_searches', models.IntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('started', models.DateTimeField(blank=True, null=True)),
                ('finished', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_jobs', to='bom.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='UserAISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_api_key', models.TextField(blank=True)),
                ('model', models.CharField(default='claude-opus-5', max_length=50)),
                ('monthly_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'user AI settings',
            },
        ),
    ]
