# Generated by Django 5.2.6 on 2026-08-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0032_ai_settings_and_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='naming_guide',
            field=models.TextField(blank=True),
        ),
    ]
