# Generated by Django 5.2.6 on 2026-08-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0033_team_naming_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='aijob',
            name='progress',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='useraisettings',
            name='monthly_budget',
            field=models.DecimalField(blank=True, decimal_places=2, default=10, max_digits=8, null=True),
        ),
    ]
