# Generated by Django 5.2.6 on 2026-08-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0034_ai_budget_default_and_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='aijob',
            name='cancel_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aijob',
            name='progress_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
