# Generated by Django 5.2.6 on 2026-08-22 22:05

import bom.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0035_ai_job_cancel_and_heartbeat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalnamedpiece',
            name='suffix',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^(?!\\.)(?!.*\\.$)[0-9A-Z.-]*$', 'Only uppercase letters, numbers, dashes and dots are allowed (a dot only in the middle).')]),
        ),
        migrations.AlterField(
            model_name='historicalpart',
            name='reference',
            field=models.CharField(db_index=True, default=bom.models.get_default_reference, max_length=100, validators=[django.core.validators.RegexValidator('^(?!\\.)(?!.*\\.$)[0-9A-Z.-]*$', 'Only uppercase letters, numbers, dashes and dots are allowed (a dot only in the middle).')]),
        ),
        migrations.AlterField(
            model_name='historicalpartsource',
            name='partcode',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalpcbpart',
            name='reference',
            field=models.CharField(db_index=True, default=bom.models.get_default_reference, max_length=100, validators=[django.core.validators.RegexValidator('^(?!\\.)(?!.*\\.$)[0-9A-Z.-]*$', 'Only uppercase letters, numbers, dashes and dots are allowed (a dot only in the middle).')]),
        ),
        migrations.AlterField(
            model_name='historicalpcbsubassembly',
            name='reference',
            field=models.CharField(db_index=True, default=bom.models.get_default_reference, max_length=100, validators=[django.core.validators.RegexValidator('^(?!\\.)(?!.*\\.$)[0-9A-Z.-]*$', 'Only uppercase letters, numbers, dashes and dots are allowed (a dot only in the middle).')]),
        ),
        migrations.AlterField(
            model_name='historicalsubassembly',
            name='reference',
            field=models.CharField(db_index=True, default=bom.models.get_default_reference, max_length=100, validators=[django.core.validators.RegexValidator('^(?!\\.)(?!.*\\.$)[0-9A-Z.-]*$', 'Only uppercase letters, numbers, dashes and dots are allowed (a dot only in the middle).')]),
        ),
        migrations.AlterField(
            model_name='namedpiece',
            name='suffix',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^(?!\\.)(?!.*\\.$)[0-9A-Z.-]*$', 'Only uppercase letters, numbers, dashes and dots are allowed (a dot only in the middle).')]),
        ),
        migrations.AlterField(
            model_name='part',
            name='reference',
            field=models.CharField(default=bom.models.get_default_reference, max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^(?!\\.)(?!.*\\.$)[0-9A-Z.-]*$', 'Only uppercase letters, numbers, dashes and dots are allowed (a dot only in the middle).')]),
        ),
        migrations.AlterField(
            model_name='partsource',
            name='partcode',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='subassembly',
            name='reference',
            field=models.CharField(default=bom.models.get_default_reference, max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^(?!\\.)(?!.*\\.$)[0-9A-Z.-]*$', 'Only uppercase letters, numbers, dashes and dots are allowed (a dot only in the middle).')]),
        ),
    ]
