# Generated by Django 5.2.6 on 2026-08-22 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0036_partsource_partcode_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpartsource',
            name='supplier',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='partsource',
            name='supplier',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
