# Generated by Django 5.2.6 on 2026-08-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0038_aithread_aimessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aijob',
            name='cleared',
            field=models.BooleanField(default=False),
        ),
    ]
