# Generated by Django 5.2.6 on 2026-08-23 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0039_aijob_cleared'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='hs_lookup',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
