# Generated by Django 5.2.6 on 2026-08-23 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0040_team_hs_lookup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='lead_time',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='historicalpartsource',
            name='lead_time',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='partsource',
            name='lead_time',
            field=models.IntegerField(default=7),
        ),
    ]
